name: apps_login_register
description: "Flutter Project Login & Register"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_cli: ^1.8.1
  oauth2: ^2.0.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets/:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
