// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_jbXLY7c_0nyTVF-famQUFffZI8OjSUg',
    appId: '1:271612060907:web:2b6ef4ca123db0745d8aae',
    messagingSenderId: '271612060907',
    projectId: 'firm-moonlight-420708',
    authDomain: 'firm-moonlight-420708.firebaseapp.com',
    storageBucket: 'firm-moonlight-420708.appspot.com',
    measurementId: 'G-TN88RYHG0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqSaoR4Y0ecZG7WY00Susj48Vaifxk7w',
    appId: '1:271612060907:android:f953d44de3b4bfd35d8aae',
    messagingSenderId: '271612060907',
    projectId: 'firm-moonlight-420708',
    storageBucket: 'firm-moonlight-420708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjL8F9TUTmLPZfbekrMHJp1eWXQcU9uE',
    appId: '1:271612060907:ios:7d4fe9b006701e705d8aae',
    messagingSenderId: '271612060907',
    projectId: 'firm-moonlight-420708',
    storageBucket: 'firm-moonlight-420708.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjL8F9TUTmLPZfbekrMHJp1eWXQcU9uE',
    appId: '1:271612060907:ios:7d4fe9b006701e705d8aae',
    messagingSenderId: '271612060907',
    projectId: 'firm-moonlight-420708',
    storageBucket: 'firm-moonlight-420708.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_jbXLY7c_0nyTVF-famQUFffZI8OjSUg',
    appId: '1:271612060907:web:caabb3307ca1f6455d8aae',
    messagingSenderId: '271612060907',
    projectId: 'firm-moonlight-420708',
    authDomain: 'firm-moonlight-420708.firebaseapp.com',
    storageBucket: 'firm-moonlight-420708.appspot.com',
    measurementId: 'G-ZKZQ1CB5X3',
  );

}