// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcmjTJ5q-1mT72z0Pcq_aYa02rcsFcNbk',
    appId: '1:556216539678:android:bd061aaeb58ab61c1dec0f',
    messagingSenderId: '556216539678',
    projectId: 'flutter-firebase-app-c9b52',
    storageBucket: 'flutter-firebase-app-c9b52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_p81AaZzoD0rXFtJfpiL9H3pNeEGEoDg',
    appId: '1:556216539678:ios:31886cb3041907d91dec0f',
    messagingSenderId: '556216539678',
    projectId: 'flutter-firebase-app-c9b52',
    storageBucket: 'flutter-firebase-app-c9b52.firebasestorage.app',
    iosBundleId: 'com.dea.firebaseApplication',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3guDAz40pv7eTWlTpBZfQ6d8zrpOyk0',
    appId: '1:556216539678:web:f1f6db477678eec41dec0f',
    messagingSenderId: '556216539678',
    projectId: 'flutter-firebase-app-c9b52',
    authDomain: 'flutter-firebase-app-c9b52.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-c9b52.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_p81AaZzoD0rXFtJfpiL9H3pNeEGEoDg',
    appId: '1:556216539678:ios:31886cb3041907d91dec0f',
    messagingSenderId: '556216539678',
    projectId: 'flutter-firebase-app-c9b52',
    storageBucket: 'flutter-firebase-app-c9b52.firebasestorage.app',
    iosBundleId: 'com.dea.firebaseApplication',
  );

}