name: firebase_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_native_splash: ^2.4.2
  flutter: 
    sdk: flutter
  get: ^4.6.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/awal.jpg

flutter_native_splash:
  color: "#FFFFFF" # Warna background splash screen
  image: assets/awal.jpg # Path gambar logo
  android: true # Aktifkan splash screen untuk Android
  ios: true # Aktifkan splash screen untuk iOS
  web: true # Aktifkan splash screen untuk Web

