// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQaWRGK2vHu3b0LVGMhyFqhNutOjZlfw',
    appId: '1:1054428659857:web:95ff7797dab1ceb1f37f30',
    messagingSenderId: '1054428659857',
    projectId: 'my-firebase-project-f5f3a',
    authDomain: 'my-firebase-project-f5f3a.firebaseapp.com',
    storageBucket: 'my-firebase-project-f5f3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5WS91_5ysFUuZ1cLnlhYbjlKDE2CyzrQ',
    appId: '1:1054428659857:android:6e3594a36e720ca7f37f30',
    messagingSenderId: '1054428659857',
    projectId: 'my-firebase-project-f5f3a',
    storageBucket: 'my-firebase-project-f5f3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXSKLKCjPgPHtAJpBE2vN9ntyG7n7jf0Y',
    appId: '1:1054428659857:ios:b83eb4be389deeb4f37f30',
    messagingSenderId: '1054428659857',
    projectId: 'my-firebase-project-f5f3a',
    storageBucket: 'my-firebase-project-f5f3a.appspot.com',
    iosBundleId: 'com.dea.firebaseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXSKLKCjPgPHtAJpBE2vN9ntyG7n7jf0Y',
    appId: '1:1054428659857:ios:b83eb4be389deeb4f37f30',
    messagingSenderId: '1054428659857',
    projectId: 'my-firebase-project-f5f3a',
    storageBucket: 'my-firebase-project-f5f3a.appspot.com',
    iosBundleId: 'com.dea.firebaseApplication',
  );
}
