name: resep_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  uuid: ^4.5.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^1.0.8
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  sqflite: ^2.3.3
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.2
  palette_generator: ^0.3.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  assets:
  - assets/images/
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
      - asset: assets/fonts/Poppins-ExtraBold.ttf
      - asset: assets/fonts/Poppins-Black.ttf
  uses-material-design: true

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/logo2.png
  color_dark: '#121212'
  image_dark: assets/images/logo2.png
  android_12:
    image: assets/images/logo2.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/logo2.png
    icon_background_color_dark: '#121212'
  web: false

